name: jsAction
description: calculator to test JavaScript Action
inputs:
  number1:
    required: true
    default: 0
  number2:
    required: true
    default: 0
outputs:
  result:
    description: "output of sum of the 2 numbers"

runs:
  using: "node20"
  main: "dist/index.js"